# ==================== 规则集 ====================
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list

ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]MATCH

# ==================== 策略组（顺序非常重要！） ====================
custom_proxy_group=🌍 全局代理`select`[]🚀 节点选择`.*               # 必须放在第一位！Global模式主组

custom_proxy_group=🚀 节点选择`select`[]DIRECT`.*                    # 节点选择

custom_proxy_group=🎯 全球直连`select`[]DIRECT`🚀 节点选择          # 直连备用

enable_rule_generator=true
overwrite_original_rules=true
